import {useEffect, useMemo, useRef} from "react";
import {Label, Stack, Text, TextInput} from "@sanity/ui";
import {set, useFormValue} from "sanity";
import type {ObjectInputProps} from "sanity";

type LocalizedPosition = {en?: string; zh?: string};
type Role = "postdoc" | "phd" | "masterToPhd" | "master" | "graduated" | "other";

const roleLabels: Record<Exclude<Role, "other">, {zh: string; en: string}> = {
  postdoc: {zh: "博士后", en: "Postdoctoral Fellow"},
  phd: {zh: "博士研究生", en: "Ph.D. student"},
  masterToPhd: {zh: "硕转博", en: "Master’s-to-Ph.D. student"},
  master: {zh: "硕士研究生", en: "Master’s student"},
  graduated: {zh: "毕业生", en: "Graduate"},
};

function generatedPosition(year: unknown, role: unknown): LocalizedPosition | undefined {
  if (typeof role !== "string" || role === "other" || !(role in roleLabels)) return undefined;
  const label = roleLabels[role as Exclude<Role, "other">];
  if (role === "graduated") return label;
  if (!Number.isInteger(year)) return undefined;
  return {zh: `${year}级${label.zh}`, en: `${year} cohort · ${label.en}`};
}

export function PersonPositionInput(props: ObjectInputProps<LocalizedPosition>) {
  const {value, onChange, readOnly} = props;
  const documentId = useFormValue(["_id"]) as string | undefined;
  const year = useFormValue(["enrollmentYear"]);
  const role = useFormValue(["memberRole"]) as Role | undefined;
  const generated = useMemo(() => generatedPosition(year, role), [role, year]);
  const autoGenerated = useRef<LocalizedPosition | undefined>(undefined);
  const previousDocumentId = useRef(documentId);

  useEffect(() => {
    if (previousDocumentId.current === documentId) return;
    previousDocumentId.current = documentId;
    autoGenerated.current = undefined;
  }, [documentId]);

  useEffect(() => {
    // Published/read-only documents can render this input without an editable draft.
    if (readOnly) return;

    const current = {zh: value?.zh?.trim() ?? "", en: value?.en?.trim() ?? ""};
    const isEmpty = !current.zh && !current.en;
    const followsPreviousTemplate = autoGenerated.current && current.zh === autoGenerated.current.zh && current.en === autoGenerated.current.en;

    // Switching from an untouched generated template to “other” clears that
    // template so the editor can enter a genuinely custom bilingual status.
    if (!generated) {
      if (role === "other" && followsPreviousTemplate) onChange(set({zh: "", en: ""}));
      autoGenerated.current = undefined;
      return;
    }

    // Fill a blank field, or refresh a value that was previously generated and not edited.
    if (isEmpty || followsPreviousTemplate) {
      if (current.zh !== generated.zh || current.en !== generated.en) onChange(set(generated));
      autoGenerated.current = generated;
      return;
    }

    // Existing values that already match the template can continue to follow year/role changes.
    if (current.zh === generated.zh && current.en === generated.en) autoGenerated.current = generated;
  }, [generated, onChange, readOnly, role, value?.en, value?.zh]);

  const updatePosition = (language: "zh" | "en", text: string) => {
    // Any direct edit opts out of future automatic replacement.
    autoGenerated.current = undefined;
    onChange(set({...value, [language]: text}));
  };

  const helperText = role === "other"
    ? "“其他”不会自动生成身份/状态，请直接填写中文和英文内容。"
    : generated
      ? "已自动填入，可自行修改；选择毕业生时不添加入学年份。"
      : "请先选择入学年份和成员身份，系统会自动填入对应身份。";

  return <Stack space={3}>
    <Text size={1} muted>{helperText}</Text>
    <Stack space={2}>
      <Label size={1}>中文身份/状态</Label>
      <TextInput
        {...props.elementProps}
        disabled={Boolean(readOnly)}
        readOnly={Boolean(readOnly)}
        value={value?.zh ?? ""}
        onChange={(event) => updatePosition("zh", event.currentTarget.value)}
      />
    </Stack>
    <Stack space={2}>
      <Label size={1}>English status</Label>
      <TextInput
        {...props.elementProps}
        disabled={Boolean(readOnly)}
        readOnly={Boolean(readOnly)}
        value={value?.en ?? ""}
        onChange={(event) => updatePosition("en", event.currentTarget.value)}
      />
    </Stack>
  </Stack>;
}
