import {useEffect, useMemo, useRef} from "react";
import {Stack, Text, TextInput} from "@sanity/ui";
import {set, useFormValue} from "sanity";
import type {ObjectInputProps} from "sanity";

type LocalizedPosition = {en?: string; zh?: string};
type Role = "postdoc" | "phd" | "masterToPhd" | "master" | "graduated" | "other";

const roleLabels: Record<Exclude<Role, "other">, {zh: string; en: string}> = {
  postdoc: {zh: "博士后", en: "Postdoctoral Fellow"},
  phd: {zh: "博士生", en: "Ph.D. student"},
  masterToPhd: {zh: "硕转博", en: "Master's-to-Ph.D. student"},
  master: {zh: "硕士生", en: "Master's student"},
  graduated: {zh: "已毕业", en: "Graduate"},
};

function generatedPosition(year: unknown, role: unknown): LocalizedPosition | undefined {
  if (!Number.isInteger(year) || typeof role !== "string" || role === "other" || !(role in roleLabels)) return undefined;
  const label = roleLabels[role as Exclude<Role, "other">];
  return {zh: `北京大学教育学院${year}级${label.zh}`, en: `${label.en}, Peking University Graduate School of Education, ${year}`};
}

export function PersonPositionInput(props: ObjectInputProps<LocalizedPosition>) {
  const {value, onChange, readOnly} = props;
  const documentId = useFormValue(["_id"]) as string | undefined;
  const year = useFormValue(["enrollmentYear"]);
  const role = useFormValue(["memberRole"]) as Role | undefined;
  const generated = useMemo(() => generatedPosition(year, role), [role, year]);
  const autoGenerated = useRef<LocalizedPosition | undefined>(undefined);
  const previousDocumentId = useRef(documentId);

  useEffect(() => {
    if (previousDocumentId.current === documentId) return;
    previousDocumentId.current = documentId;
    autoGenerated.current = undefined;
  }, [documentId]);

  useEffect(() => {
    // Published/read-only documents can render this input without an editable draft.
    if (readOnly || !generated) return;

    const current = {zh: value?.zh?.trim() ?? "", en: value?.en?.trim() ?? ""};
    const isEmpty = !current.zh && !current.en;
    const followsPreviousTemplate = autoGenerated.current && current.zh === autoGenerated.current.zh && current.en === autoGenerated.current.en;

    // Fill a blank field, or refresh a value that was previously generated and not edited.
    if (isEmpty || followsPreviousTemplate) {
      if (current.zh !== generated.zh || current.en !== generated.en) onChange(set(generated));
      autoGenerated.current = generated;
      return;
    }

    // Existing values that already match the template can continue to follow year/role changes.
    if (current.zh === generated.zh && current.en === generated.en) autoGenerated.current = generated;
  }, [generated, onChange, readOnly, value?.en, value?.zh]);

  const updatePosition = (language: "zh" | "en", text: string) => {
    // Any direct edit opts out of future automatic replacement.
    autoGenerated.current = undefined;
    onChange(set({...value, [language]: text}));
  };

  return <Stack space={3}>
    <Text size={1} muted>{generated ? "已根据入学年份和成员身份自动填入，可自行修改。" : "请先选择入学年份和成员身份，系统会自动填入对应身份。"}</Text>
    <TextInput {...props.elementProps} readOnly={readOnly} value={value?.zh ?? ""} placeholder="中文身份/状态" onChange={(event) => { if (!readOnly) updatePosition("zh", event.currentTarget.value); }} />
    <TextInput {...props.elementProps} readOnly={readOnly} value={value?.en ?? ""} placeholder="English status" onChange={(event) => { if (!readOnly) updatePosition("en", event.currentTarget.value); }} />
  </Stack>;
}
